[application]

[web.app]

# HTML title tag content
title = "task_tracker"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]
assets = ["assets"]
# Javascript code file
# serve: [dev-server] only
script = []

[tailwind]
input = "assets/input.css"

[bundle]
identifier = "com.mycompany"
publisher = "Your Name"
icon = ["assets/favicon.ico", "assets/icons/icon_128x128.png"]
short_description = "My Dioxus app"

[bundle.macos]
minimum_system_version = "10.13"
signing_identity = "-"   # "-" = ad-hoc, no Apple Developer account needed
hardened_runtime = false
